In [1]:
import numpy as np
import pandas as pd

## Fly

In [6]:
data = pd.read_csv('fly.txt', delimiter=' ', names=['s', 't', 'w'])
data

s           t    w
0        264083994   390356988    1
1        264083994  1096859621    1
2        264083994  5813021485    1
3        264083994  5813057153    1
4        297572076   575063620    1
5        297572076  1066511487    1
6        297572076  1079143870    1
7        297572076  1168120366    1
8        297572076  1172623224    1
9        297572076  1229844484    1
10       297572076  1346645554    1
11       297572076  1498582292    1
12       297572076  1530704811    1
13       297572076  1657180902    1
14       297572076  5813022753    1
15       297572076  5813054101    1
16       297572076  5813054443    1
17       297572076  5813058236    1
18       324370873   893642012    1
19       324370873   944132752    1
20       324370873  1198132041    1
21       324370873  1260542968    1
22       324370873  5812998963    1
23       324370873  5813020751    1
24       324370873  5813087952    1
25       328010530   756502912    1
26       328010530   821340054    1
27       328010530   912601209    1
28       328010530  1072063538    1
29       328010530  1077122311    1
...            ...         ...  ...
101153  1037328706   918529614   90
101154  1191315642  1629206279   90
101155  5813067929  1873086710   91
101156  1037328706   892609630   94
101157  1437302815  1356772884   95
101158  1128274593  5813020795   97
101159  1191315642  5813054443   98
101160  2124762952  1873738899   99
101161  1191315642  1597157083  100
101162  1037328706   793815358  104
101163  1343403608  1873086710  104
101164  1282676872  1290209390  105
101165  1381277138  1290209390  107
101166  5813068748  1873086710  124
101167   697882667  2124762952  131
101168  5813056423  5813022538  131
101169   883514695  1282348408  136
101170  1037328706  1783362106  137
101171  5813056423  1444351896  146
101172  1873086710  5813068748  148
101173   912601209  2124762952  203
101174  5813067929  1343403608  208
101175  5813075715  5901222742  251
101176  5813061112  2124762952  254
101177  1343403608  2124762952  268
101178  2124762952  1936507376  377
101179  2124762952  1748929680  401
101180  5813061218  1343403608  562
101181  1873086710  1343403608  692
101182  5813061218  2124762952  793

[101183 rows x 3 columns]

In [32]:
#Получить уникальные номера вершинок

In [49]:
def is_exist(lst, i):
    for el in lst:
        if i == el:
            return True
    return False

In [50]:
lst = []
for i in data['s']:
    if not is_exist(lst, i):
        lst.append(i)

In [51]:
for i in data['t']:
    if not is_exist(lst, i):
        lst.append(i)

In [52]:
len(lst)

3738

In [53]:
data['s_fix'] = data['s'].apply(lambda x: lst.index(x) + 1)

In [54]:
data['t_fix'] = data['t'].apply(lambda x: lst.index(x) + 1)

In [55]:
data

s           t    w  s_fix  t_fix
0        264083994   390356988    1      1      6
1        264083994  1096859621    1      1   2896
2        264083994  5813021485    1      1   2627
3        264083994  5813057153    1      1   2761
4        297572076   575063620    1      2     26
5        297572076  1066511487    1      2    281
6        297572076  1079143870    1      2    307
7        297572076  1168120366    1      2    503
8        297572076  1172623224    1      2    533
9        297572076  1229844484    1      2    662
10       297572076  1346645554    1      2    955
11       297572076  1498582292    1      2   1209
12       297572076  1530704811    1      2   1298
13       297572076  1657180902    1      2   1579
14       297572076  5813022753    1      2   2638
15       297572076  5813054101    1      2   2745
16       297572076  5813054443    1      2   2747
17       297572076  5813058236    1      2   2765
18       324370873   893642012    1      3    126
19       324370873   944132752    1      3    159
20       324370873  1198132041    1      3    576
21       324370873  1260542968    1      3    758
22       324370873  5812998963    1      3   2567
23       324370873  5813020751    1      3   2622
24       324370873  5813087952    1      3   2822
25       328010530   756502912    1      4     51
26       328010530   821340054    1      4     70
27       328010530   912601209    1      4    128
28       328010530  1072063538    1      4    288
29       328010530  1077122311    1      4   2897
...            ...         ...  ...    ...    ...
101153  1037328706   918529614   90    249    137
101154  1191315642  1629206279   90    563   1544
101155  5813067929  1873086710   91   2786   2009
101156  1037328706   892609630   94    249    114
101157  1437302815  1356772884   95   1099    981
101158  1128274593  5813020795   97    389   2623
101159  1191315642  5813054443   98    563   2747
101160  2124762952  1873738899   99   2306   2012
101161  1191315642  1597157083  100    563   1487
101162  1037328706   793815358  104    249     69
101163  1343403608  1873086710  104    929   2009
101164  1282676872  1290209390  105    797    850
101165  1381277138  1290209390  107   1028    850
101166  5813068748  1873086710  124   2790   2009
101167   697882667  2124762952  131     39   2306
101168  5813056423  5813022538  131   2757   2946
101169   883514695  1282348408  136     94    795
101170  1037328706  1783362106  137    249   1855
101171  5813056423  1444351896  146   2757   1145
101172  1873086710  5813068748  148   2009   2790
101173   912601209  2124762952  203    128   2306
101174  5813067929  1343403608  208   2786    929
101175  5813075715  5901222742  251   2803   2871
101176  5813061112  2124762952  254   2773   2306
101177  1343403608  2124762952  268    929   2306
101178  2124762952  1936507376  377   2306   2119
101179  2124762952  1748929680  401   2306   1760
101180  5813061218  1343403608  562   2775    929
101181  1873086710  1343403608  692   2009    929
101182  5813061218  2124762952  793   2775   2306

[101183 rows x 5 columns]

In [56]:
new_list = [str(i)+'\n' for i in data['s_fix'].to_list()]
with open('fly_start_neurons.txt', 'w') as f:
          f.writelines(new_list)

In [57]:
new_list = [str(i)+'\n' for i in data['t_fix'].to_list()]
with open('fly_end_neurons.txt', 'w') as f:
          f.writelines(new_list)

## C elegans

In [75]:
data = pd.read_csv('celegans.txt', delimiter=' ', names=['s', 't', 'w'])
data

s      t    w
0      I1L     I6    1
1      I1L   pm4D    1
2      I1R     I3    1
3      I1R     M1    1
4      I1R    M2L    1
5      I1R    M3L    1
6      I1R     MI    1
7      I1R   NSML    1
8      I1R   pm4D    1
9      I1R  pm5VR    1
10     I2L     M1    1
11     I2L  pm3VL    1
12     I2L   pm5D    1
13     I2L  pm5VR    1
14     I2L   e3VL    1
15     I2R    I1R    1
16     I2R    MCL    1
17     I2R    pm1    1
18     I2R  pm3VR    1
19     I2R  pm4VL    1
20     I2R  pm5VL    1
21     I2R   e3VR    1
22      I3    I1L    1
23      I3    I1R    1
24      I3     I6    1
25      I3    MCL    1
26      I3     MI    1
27      I4     MI    1
28      I4   pm4D    1
29      I5    I2R    1
...    ...    ...  ...
5276   HOA    PVZ   82
5277  CP09   CP07   82
5278   HOA   PHCR   84
5279  R2BR   PHCR   86
5280  R7BR    PVV   86
5281  NSML     bm   88
5282  AWAR   AIZR   88
5283  R7BR    PDC   90
5284   HOA    AVG   90
5285  R4AR   R4AL   91
5286  R9BL    EF2   91
5287   HOB    HOA   94
5288  R3BR    EF3   98
5289  R2BL   PHCL   99
5290  RIAR  RMDDR  107
5291  RIAR  RMDVL  113
5292  PCAL    PVX  113
5293  AIYR   RIBR  117
5294  AIYR   RIAR  121
5295  PCCL  gonad  121
5296  PCCR  gonad  122
5297   HOA   PHCL  134
5298  CP09    PDB  134
5299  AIYL   RIBL  142
5300  SABD    hyp  142
5301  AIYR   AIZR  152
5302  AIYL   AIZL  157
5303  PCAR    PVX  160
5304  AIYL   RIAL  171
5305  CP09    PVV  194

[5306 rows x 3 columns]

In [76]:
data = data[data['s'] != data['t']]
data

s      t    w
0      I1L     I6    1
1      I1L   pm4D    1
2      I1R     I3    1
3      I1R     M1    1
4      I1R    M2L    1
5      I1R    M3L    1
6      I1R     MI    1
7      I1R   NSML    1
8      I1R   pm4D    1
9      I1R  pm5VR    1
10     I2L     M1    1
11     I2L  pm3VL    1
12     I2L   pm5D    1
13     I2L  pm5VR    1
14     I2L   e3VL    1
15     I2R    I1R    1
16     I2R    MCL    1
17     I2R    pm1    1
18     I2R  pm3VR    1
19     I2R  pm4VL    1
20     I2R  pm5VL    1
21     I2R   e3VR    1
22      I3    I1L    1
23      I3    I1R    1
24      I3     I6    1
25      I3    MCL    1
26      I3     MI    1
27      I4     MI    1
28      I4   pm4D    1
29      I5    I2R    1
...    ...    ...  ...
5276   HOA    PVZ   82
5277  CP09   CP07   82
5278   HOA   PHCR   84
5279  R2BR   PHCR   86
5280  R7BR    PVV   86
5281  NSML     bm   88
5282  AWAR   AIZR   88
5283  R7BR    PDC   90
5284   HOA    AVG   90
5285  R4AR   R4AL   91
5286  R9BL    EF2   91
5287   HOB    HOA   94
5288  R3BR    EF3   98
5289  R2BL   PHCL   99
5290  RIAR  RMDDR  107
5291  RIAR  RMDVL  113
5292  PCAL    PVX  113
5293  AIYR   RIBR  117
5294  AIYR   RIAR  121
5295  PCCL  gonad  121
5296  PCCR  gonad  122
5297   HOA   PHCL  134
5298  CP09    PDB  134
5299  AIYL   RIBL  142
5300  SABD    hyp  142
5301  AIYR   AIZR  152
5302  AIYL   AIZL  157
5303  PCAR    PVX  160
5304  AIYL   RIAL  171
5305  CP09    PVV  194

[5246 rows x 3 columns]

In [77]:
lst = []
for i in data['s']:
    if not is_exist(lst, i):
        lst.append(i)
for i in data['t']:
    if not is_exist(lst, i):
        lst.append(i)

In [78]:
len(lst)

559

In [79]:
data['s_fix'] = data['s'].apply(lambda x: lst.index(x) + 1)
data['t_fix'] = data['t'].apply(lambda x: lst.index(x) + 1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [80]:
data

s      t    w  s_fix  t_fix
0      I1L     I6    1      1      8
1      I1L   pm4D    1      1    376
2      I1R     I3    1      2      5
3      I1R     M1    1      2      9
4      I1R    M2L    1      2     10
5      I1R    M3L    1      2     12
6      I1R     MI    1      2     16
7      I1R   NSML    1      2     17
8      I1R   pm4D    1      2    376
9      I1R  pm5VR    1      2    377
10     I2L     M1    1      3      9
11     I2L  pm3VL    1      3    378
12     I2L   pm5D    1      3    379
13     I2L  pm5VR    1      3    377
14     I2L   e3VL    1      3    380
15     I2R    I1R    1      4      2
16     I2R    MCL    1      4    374
17     I2R    pm1    1      4    381
18     I2R  pm3VR    1      4    382
19     I2R  pm4VL    1      4    383
20     I2R  pm5VL    1      4    384
21     I2R   e3VR    1      4    385
22      I3    I1L    1      5      1
23      I3    I1R    1      5      2
24      I3     I6    1      5      8
25      I3    MCL    1      5    374
26      I3     MI    1      5     16
27      I4     MI    1      6     16
28      I4   pm4D    1      6    376
29      I5    I2R    1      7      4
...    ...    ...  ...    ...    ...
5276   HOA    PVZ   82    264    281
5277  CP09   CP07   82    349    304
5278   HOA   PHCR   84    264     57
5279  R2BR   PHCR   86    234     57
5280  R7BR    PVV   86    254    278
5281  NSML     bm   88     17    390
5282  AWAR   AIZR   88    350    320
5283  R7BR    PDC   90    254    289
5284   HOA    AVG   90    264    106
5285  R4AR   R4AL   91    240    239
5286  R9BL    EF2   91    261    287
5287   HOB    HOA   94    265    264
5288  R3BR    EF3   98    238    288
5289  R2BL   PHCL   99    233     56
5290  RIAR  RMDDR  107    127    146
5291  RIAR  RMDVL  113    127    149
5292  PCAL    PVX  113    266    279
5293  AIYR   RIBR  117     84    323
5294  AIYR   RIAR  121     84    127
5295  PCCL  gonad  121    270    404
5296  PCCR  gonad  122    271    404
5297   HOA   PHCL  134    264     56
5298  CP09    PDB  134    349    185
5299  AIYL   RIBL  142     83    108
5300  SABD    hyp  142    366    394
5301  AIYR   AIZR  152     84    320
5302  AIYL   AIZL  157     83     87
5303  PCAR    PVX  160    267    279
5304  AIYL   RIAL  171     83    126
5305  CP09    PVV  194    349    278

[5246 rows x 5 columns]

In [81]:
new_list = [str(i)+'\n' for i in data['s_fix'].to_list()]
with open('celegans_start_neurons.txt', 'w') as f:
          f.writelines(new_list)

In [82]:
new_list = [str(i)+'\n' for i in data['t_fix'].to_list()]
with open('celegans_end_neurons.txt', 'w') as f:
          f.writelines(new_list)

## Случайный граф
Для проверки работы двух библиотек

In [110]:
s = np.arange(1,21)
t = np.arange(1,21)

In [111]:
np.random.shuffle(s)
np.random.shuffle(t)
w = np.random.randint(1, 5, 20)

In [112]:
w.sort()
w

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4])

In [113]:
print(s)
print(t)

[15  6 19  4 17  1  9  7 12  2 20  3 10 18 16  5 11  8 13 14]
[20 18  2 12 15 16  5 10  4  3  9 13 14  1  8  7 19 17 11  6]


In [114]:
new_list = [str(i)+'\n' for i in s]
with open('s.txt', 'w') as f:
          f.writelines(new_list)
new_list = [str(i)+'\n' for i in t]
with open('t.txt', 'w') as f:
          f.writelines(new_list)

In [115]:
new_list = [str(s[i]) + ' ' + str(t[i]) + ' ' + str(w[i]) +'\n' for i in range(0,20)]
with open('edges.txt', 'w') as f:
          f.writelines(new_list)